apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend
  namespace: my-namespace
spec:
  egress:
  - ports:
    - 53
    protocol: UDP
    to:
    - {}
  - ports:
    - 53
    protocol: TCP
    to:
    - {}
  ingress:
  - from:
    - ports:
      - 8080
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
  - Ingress
  - Egress
